#!/bin/bash
#Lucy S
#Version 1: Takes a one-digit number and echoes the word
#Version 2: Takes a one or two digit number and passes it to a function (speak_number_tens) which says the tens place (special for 10-19) and then sends the digit in the ones place through speak_number_ones.



function speak_number_ones  () {
read answer
    case ${answer:1} in
	?1) echo "one" ;;
	?2) echo "two" ;;
	?3) echo "three" ;;
	?4) echo "four" ;;
	?5) echo "five" ;;
	?6) echo "six" ;;
	    ?7) echo "seven" ;;
	    ?8) echo "eight" ;;
	    ?9) echo "nine" ;;	
	    ?0) echo "zero" ;;
	    *) echo "That is not a two-digit number. Please try again." ; return ;;
    esac
}
function speak_number_tens () {
    read -p "please type a number between 0 and 100" answer
echo ${answer:0:1}
    case $answer in
	1?) echo "ten " ;;
	2?) echo "twenty " ;;
	3?) echo "thirty " ;;
	4?) echo "fourty" ;;
	5?) echo "fifty" ;;
	6?) echo "sixty" ;;
	7?) echo "seventy" ;;
	8?) echo "eighty" ;;
	9?) echo "ninety" ;;
    esac
    speak_number_ones 
    return
}

echo "Welcome!"
while [ 1 ]
do    
    speak_number_tens
echo "Thank you!"
done
exit
