#!/bin/bash
#there's not really anything here
#I did this so there's at least something in foo

thing=Hello
thing2=Goodbye
thing3="See you soon!"

echo "$thing"
echo "what's your name?"
read varname
echo it\'s nice to meet you $varname
read -p "Are you leaving me? [y/n]" answer
if [[ $answer = y ]] ; then
echo "$thing2"
else
    echo "I'm glad you stayed."
    read -p "you should really go though. [y/n]" answer2
    if [[ $answer2 = y ]] ; then
	echo "$thing3"
    else
	echo "I promise I'll see you again, bye!"
	exit
	fi
fi
