#!/bin/bash
#there's not really anything here
#I did this so there's at least something in foo

thing=Hello
thing2=Goodbye
thing3="See you soon!"
# date= $ date

echo "$thing"
echo "what's your name?"
read varname
echo it\'s nice to meet you $varname
read -p "Are you leaving me? [y/n]" answer
if [[ $answer = y ]] ; then
    echo "$thing2"
    exit
fi   
    read -p "Do you like cake? [y/n]" answer3
    if [[ $answer3 = y ]] ; then
	echo "The cake is a lie"
	echo "$thing2"
	exit
    else
	echo "The cake is a lie anyway"
	echo "Which do you like?"
	read dessert
	echo I like $dessert too!
	read -p "Do you want to know something? [y/n]" answer4
	if [[ $answer4 = y ]] ; then
	    echo "today is $(date '+%A %D') !"
	    else 
	echo "I'm glad you stayed."
    read -p "you should really go though. [y/n]" answer2
    if [ $answer2 = y ] ; then
	echo "$thing3"
    else
	echo "I promise I'll see you again, bye!"
	exit
	fi
fi
fi

